name: Generuj Dokumentacje

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Pobranie repozytorium
              uses: actions/checkout@v4

            - name: Konfiguracja Pythona
              uses: actions/setup-python@v5
              with:
                  python-version: 3.x

            - name: Instalacja zależności
              run: |
                  pip install mkdocs-material mkdocstrings[python]

            - name: Budowanie i publikacja (GitHub Pages)
              run: mkdocs gh-deploy --force
