site_name: Firmowa Dokumentacja (Projekt 18)
site_description: Ustandaryzowana i wersjonowana dokumentacja dla projektów Python i Scala.
theme:
    name: material
    logo: material/library
    favicon: material/library
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: deep purple
          accent: deep purple
          toggle:
              icon: material/weather-night
              name: Przełącz na tryb ciemny
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep purple
          accent: deep purple
          toggle:
              icon: material/weather-sunny
              name: Przełącz na tryb jasny
    features:
        - navigation.tabs
        - navigation.top
        - navigation.instant
        - content.code.copy

extra:
    version:
        provider: mike

plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  paths: [src]

nav:
    - Strona Główna: index.md
    - Moduł Pythona (Kalkulator): calculator.md
    - Moduł Scali (API): scala.md
