site_name: Firmowa Dokumentacja (Projekt 18)
site_description: Ustandaryzowana i wersjonowana dokumentacja dla projektów Python i Scala.
site_url: https://wikigr14.github.io/Generator-dokumentacji-Python/
theme:
    name: material
    icon:
        logo: material/library
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/weather-night
              name: Przełącz na tryb ciemny
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep purple
          accent: deep purple
          toggle:
              icon: material/weather-sunny
              name: Przełącz na tryb jasny
    features:
        - navigation.tabs
        - navigation.top
        - navigation.instant
        - content.code.copy
        - content.code.annotate
        - navigation.sections
        - navigation.expand

extra:
    version:
        provider: mike

plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  paths: [src/python]

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true

nav:
    - Strona Główna: index.md
    - Moduł Pythona:
          - Kalkulator: calculator.md
          - Wzorce Projektowe: python.md
    - Architektura: architecture.md
    - Moduł Scali (API):
          - Omówienie: scala.md
